export { default as Head } from './head';
export { default as Layout } from './layout';
export { default as Nav } from './nav';
export { default as Footer } from './footer';
export { default as About } from './sections/about';
export { default as Work } from './sections/work';
export { default as Contact } from './sections/contact';
export { default as Projects } from './sections/projects';
export { default as Landing } from './sections/landing';